### ISSUE TITLE
Netlify Dev

### ISSUE THREAD

**Issue by pkafei** [porfirioribeiro/gatsby-plugin-netlify-functions#11]
The Gatsby Netlify Function ReadMe states that , _["With the release of netlify dev this package should be used anymore"](https://github.com/porfirioribeiro/gatsby-plugin-netlify-functions#gatsby-plugin-netlify-functions)_. 

The wording of this sentence is slightly confusing. Does this mean a developer should still use the Gatsby Netlify Functions Plugin, or should one use [Netlify Dev](https://github.com/netlify/cli/blob/master/docs/netlify-dev.md)?

**Comment by DavidSabine** [comment]
I have refactored my environment to entirely replace gatsby-plugins-netlify-functions with `netlify dev`.  I also use yarn workspaces (which created some additional trouble) and I just uploaded a video about this refactoring here: https://youtu.be/-bPTpVOLxfM

**Comment by porfirioribeiro** [comment]
My mistake guys, fixed it
