### ISSUE TITLE
Support Node Modules?

### ISSUE THREAD

**Issue by gil--** [porfirioribeiro/gatsby-plugin-netlify-functions#4]
Does this support building of node modules? In production it seems to fail:

```

{
  "errorMessage": "Cannot find module 'shopify-token'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:474:25)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "Object.<anonymous> (/var/task/auth.js:3:20)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)"
  ]
}
```

Where my code looks like:

```
var ShopifyToken = require('shopify-token');
```

And in package.json:

```
"shopify-token": "^3.0.3",
```

It works in gatsby develop but not once built on Netlify.

**Comment by brotzky** [comment]
Getting the same issue, `"errorMessage": "Cannot find module 'dontenv'", `
Going to give it a quick look

**Comment by brotzky** [comment]
@gil-- I ended up removing this plugin and following this tutorial: https://www.gatsbyjs.org/blog/2018-12-17-turning-the-static-dynamic/

It only took a couple minutes to setup the netlify-lambda plugin with a local proxy. Everything now works, with node modules as well. Good luck!

**Comment by gil--** [comment]
@brotzky Thanks! I actually ended up moving off Netlify functions over to Firebase functions (mainly due to the lack of support for firebase-admin).
