### ISSUE TITLE
add a reference to netlify dev?

### ISSUE THREAD

**Issue by swyxio** [porfirioribeiro/gatsby-plugin-netlify-functions#7]
hi! i work at netlify.

we launched netlify dev in april and that should make it a lot easier for many people to use netlify functions without having to use a transpile step. 

we are workign on removing this in our gatsby starter: https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/273

wonder if you'd like to point people to [netlify dev](https://github.com/netlify/netlify-dev-plugin) too!

**Comment by porfirioribeiro** [comment]
Hi, i'm sorry for the so late reply.

Been working on other stuff and somehow missed notifications on this repo :disappointed: 
Will do that now!

**Comment by swyxio** [comment]
no worries
